openapi: 3.0.3
info:
  title: NINO
  contact: {}
  version: '1.0'
  description: >
    # Overview

    ### NINO Insights

    This API enables your application to get an opinion of the riskiness of a NINO.

    Given a NINO, the response will provide:

    * Risk score from 0 (no risk) to 100 (high risk)
    * Reason providing an indication of why the risk score has been allocated
    * Correlation Id - so you can reference the transaction in any feedback
servers:
  - url: https://test-api.service.hmrc.gov.uk/misc/nino
    description: Sandbox
  - url: https://api.service.hmrc.gov.uk/misc/nino
    description: Production
paths:
  /check/insights:
    post:
      summary: NINO insights
      description: >
        Check if the provided NINO is valid
      operationId: NinoInsights
      security:
        - applicationRestricted: [ ]
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: 'docs/request.json'
            example:
              $ref: 'docs/request-sample.json'
        required: true
      responses:
        '200':
          description: ''
          headers: { }
          content:
            application/json:
              schema:
                $ref: 'docs/response.json'
              example:
                $ref: 'docs/response-sample.json'
      deprecated: false
components:
  securitySchemes:
    applicationRestricted:
      type: oauth2
      description: |
        HMRC supports OAuth 2.0 for authenticating application restricted API requests using an OAuth 2.0 Bearer Token in the AUTHORIZATION header.
        See https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/application-restricted-endpoints for details.
      flows:
        clientCredentials:
          tokenUrl: https://api.service.hmrc.gov.uk/oauth/token
          scopes: { }