#%RAML 1.0 Library

usage: Required headers

traits:
  userAgentHeader:
    headers:
      User-Agent:
        description: Calling service identifier
        type: string
        required: true
        example: calling-service
